version: 2.1

jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: |
            hadolint Dockerfile

  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run:
          name: Build and Push Docker Image
          command: |
            # Replace <your-docker-hub-username> and <your-image-name> with your Docker Hub credentials
            docker build -t gunzxx/karsajobs:latest .
            docker login -u gunzxx -p Konfirmasi_
            docker push gunzxx/karsajobs:latest

workflows:
  karsajobs-ci:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs